const isProduction =
  process.env.NODE_ENV == 'development' ? 'error' : 'warning';

module.exports = {
  parserOptions: {
    sourceType: 'module',
  },
  env: {
    es6: true,
  },
  extends: ['eslint:recommended'],
  rules: {
    // Possible Errors
    'no-async-promise-executer': 'error',
    'no-await-in-loop': 'warning',
    'no-console': isProduction,
    'no-debugger': isProduction,
    'no-empty': ['error', { allowEmptyCatch: true }],
    'no-extra-parens': ['error', 'all', { ignoreJSX: 'multi-line' }],
    'no-inner-declarations': ['error', 'both'],
    'no-misleading-character-class': 'error',
    'no-template-curly-in-string': 'warning',
    'no-unreachable': isProduction,
    'require-atomic-updates': 'warning',
    'valid-typeof': ['error', { requireStringLiterals: true }],

    // Best Practices
    'accessor-pairs': 'error',
    'array-callback-return': 'error',
    'consistent-return': ['error', { treatUndefinedAsUnspecified: true }],
    curly: ['error', 'multi-or-nest', 'consistent'],
    'default-case': 'error',
    'dot-location': ['error', 'property'],
    'dot-notation': ['error'],
    'no-alert': isProduction,
    'no-caller': 'error',
    'no-div-regex': 'error',
    'no-else-return': ['error', { allowElseIf: false }],
    'no-empty-function': 'warning',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-floating-decimal': 'error',
    'no-implicit-coercion': 'error',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-iterator': 'error',
    'no-labels': ['error', { allowLoop: true }],
    'no-loop-func': 'error',
    'no-magic-numbers': ['error', { enforceConst: true }],
    'no-multi-spaces': 'error',
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': 'warning',
    'no-proto': 'error',
    'no-restricted-properties': [
      'error',
      { property: 'prototype', message: 'Please use Object.create() instead.' },
    ],
    'no-return-assign': ['error', 'always'],
    'no-return-await': 'error',
    'no-script-url': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unused-expressions': 'error',
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-concat': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'no-warning-comments': isProduction,
    'no-with': 'error',
    'prefer-named-capture-group': 'error',
    'prefer-promise-reject-errors': 'error',
    radix: ['error', 'as-needed'],
    'require-await': 'error',
    'require-unicode-regexp': 'error',
    'vars-on-top': 'error',
    'wrap-iife': 'error',
    yoda: 'error',
    'no-label-var': 'error',
    'no-shadow': 'warning',
    'no-shadow-restricted-names': 'error',
    'no-undef-init': 'warning',
    'no-undefined': 'error',
    'no-use-before-define': ['error', 'nofunc'],

    // Node.js & CommonJS
    'callback-return': 'error',
    'global-require': 'error',
    'handle-callback-err': 'error',
    'no-buffer-constructor': 'error',
    'no-mixed-requires': 'error',
    'no-new-require': 'error',
    'no-path-concat': 'error',
    'no-process-exit': 'error',
    'no-sync': 'warning',
  },
};
